### PR TITLE
added documents for the final week of the course :-)

### PR DESCRIPTION
**Pull request by TMRert**
feelsgoodman

### CODE REVIEW

**Review by JvanderSteeg — APPROVED** [review]

**Review by grappigegovert — APPROVED** [review]
LGTM

**Comment by TMRert** [comment]
@Zerochaosz, @Fastjur, @Wolgo, @grappigegovert, @waffle-iron FINAL PR FEELSGOODMAN

**Comment by grappigegovert** [comment]
#200 hype!!

**Comment by Fastjur** [comment]
ALL ABOARD THE HYPE TRAIN. CHOO CHOO MOTHERFUCKER

**Review by Fastjur — APPROVED** [review]

**Pull request merged**
