### PR TITLE
Add pmd and checkstyle to Continuous Integration pipeline

### LINKED ISSUE #22: Add PMD to maven

### PR DESCRIPTION
**Pull request by Fastjur**
Fixes #22 and #23

### CODE REVIEW

**Comment by Wolgo** [comment]
The coveralls check still hasn't been completed, does the addition break coveralls? Could you rerun it to check?

**Comment by Fastjur** [comment]
It seems is has broken it yeah. I get this in the travis build:

```
[INFO] Skipping JaCoCo execution due to missing execution data file:/home/travis/build/Fastjur/SEM-Project/target/jacoco.exec
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 16.654 s
[INFO] Finished at: 2016-09-22T12:45:19+00:00
[INFO] Final Memory: 21M/331M
[INFO] ------------------------------------------------------------------------
```

I'll look into this

**Comment by Fastjur** [comment]
@Wolgo This has fixed it. Ready to merge.

**Comment by grappigegovert** [comment]
Looks good

**Pull request merged**
